- README.md
- package-lock.json
- package.json
- src/component.ts
- src/providers/push/socketio/index.ts
- src/providers/push/socketio/keys.ts
- src/providers/push/socketio/socketio.provider.ts
- src/providers/push/socketio/types.ts
This PR adds implementation for socket.io as a means to send real time messages from server to clients.
Test cases are pending for this.
> feat: Socket.io implementation in extension

- src/providers/push/index.ts
Hotfix for socketio to export all components of socket provider.
> chore: hotfix for socketio

- README.md
- src/providers/push/socketio/socketio.provider.ts
- src/providers/push/socketio/types.ts
add general message channel to avoid ambiguity with other channels
> chore: add general message channel 

- package-lock.json
- package.json
- src/providers/push/fcm/fcm.provider.ts
- src/providers/push/fcm/index.ts
- src/providers/push/fcm/keys.ts
- src/providers/push/fcm/types.ts
- src/providers/push/socketio/socketio.provider.ts
- src/providers/push/socketio/types.ts
Signed-off-by: mayank <mayank.nauriyal@sourcefuse.com>
This gives an implementation for FCM. 
FCM provider supports push notification mechanisms for apns, android and webpush as well.
There are 3 types of transactions available, namely 
1. Based on registration tokens
2. Based on Topics
3. Based on Conditions (For info on topics and conditions follow [url](https://firebase.google.com/docs/cloud-messaging/js/topic-messaging))
> feat: fcm implementation

- src/providers/push/fcm/fcm.provider.ts
Signed-off-by: mayank <mayank.nauriyal@sourcefuse.com>
Prettier fix added
> chore: prettier fix added

- README.md
- package-lock.json
- package.json
- src/providers/email/index.ts
- src/providers/email/nodemailer/index.ts
- src/providers/email/nodemailer/keys.ts
- src/providers/email/nodemailer/nodemailer.provider.ts
- src/providers/email/nodemailer/types.ts
- src/providers/push/fcm/fcm.provider.ts
- src/providers/push/fcm/keys.ts
Nodemailer support added.
This will work with the current interface and additional properties specific to nodemailer could be configured by sending them in options.
> feat: nodemailer support added

- .eslintignore
- package-lock.json
- package.json
- src/providers/email/nodemailer/nodemailer.provider.ts
- src/providers/email/ses/ses.provider.ts
- src/providers/push/pubnub/pubnub.provider.ts
- src/providers/push/socketio/socketio.provider.ts
- src/providers/sms/sns/sns.provider.ts
Description
Updated versions of All Loopback packages.
Type of change
> fix(version): updated version for loopback packages, fixed linting

- .cz-config.js
- .eslintignore
- .husky/commit-msg
- .husky/pre-commit
- .husky/prepare-commit-msg
- DEVELOPING.md
- commitlint.config.js
- package-lock.json
- package.json
- src/keys.ts
> feat(ci-cd): commitizen added

- src/__tests__/unit/pubnub.provider.unit.ts
- src/providers/push/fcm/fcm.provider.ts
- src/providers/push/fcm/types.ts
- src/providers/push/pubnub/pubnub.provider.ts
- src/providers/push/pubnub/types.ts
> refactor(provider): refactored fcm and pubnub provider

- package.json
Updated version of the lb4 dependencies to the latest.
> fix(notification): version update

- package-lock.json
- package.json
- src/__tests__/unit/pubnub.provider.unit.ts
GH-0
Dependencies update in lb4 notifications.
> fix(chore): update lb4 notification dependencies

- package-lock.json
- src/__tests__/unit/apns.provider.unit.ts
- src/providers/push/apns/apns.provider.ts
- src/providers/push/apns/index.ts
- src/providers/push/apns/keys.ts
- src/providers/push/apns/types.ts
- src/providers/push/index.ts
GH-46
Apns provider added to notification service
> feat(provider): apns provider added to notification service

- .vscode/settings.json
- README.md
- package.json
- src/component.ts
- src/index.ts
BREAKING CHANGE:
change import path for specific providers
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes #30
> fix(provider): fix import error for aws, pubnub and nodemailer

- src/providers/push/pubnub/pubnub.provider.ts
GH-0
**Description**
Fixed payloadtype path in pubnub provider
Type of change
Checklist:
> fix(provider): payloadtype path in pubnub provider

- package-lock.json
- package.json
remove all current vilnenrability of loopback4-notifications
GH-109
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes #109 
>  fix(chore): remove all current vulnenrability of loopback4-notifications

- README.md
- Refactored `README.md` with grammar and formatting changes
- Added the usage details for firebase cloud messaging (fcm) and apple push notifications (apns).
Fixes #114
---
Supersedes #92
> docs(provider): add fcm and apns usage instructions

- package-lock.json
- package.json
- src/__tests__/mock-sdk.ts
- src/__tests__/unit/twilio.provider.unit.ts
- src/providers/sms/twilio/types.ts
lint fixes and fixing mock-sdk in unit test
GH-120
lint fixes and fixing mock-sdk in unit test.
Overrides for twilio/jsonwebtoken
Fixes #120
> chore(deps): lint fixes and fixing mock-sdk in unit test

- README.md
- Fix typo of package name used in examples.
Fixes #81 
> docs(chore): typo and link formatting fix

- package-lock.json
- package.json
- Version 14 of Nodejs reaches its end of life
- BREAKING CHANGE:- End of life of Node v14
GH-130
Fixes #130
> feat(chore): remove support for node v14

- .sonarcloud.properties
- src/providers/push/apns/apns.provider.ts
- src/providers/push/apns/types.ts
- src/providers/push/fcm/fcm.provider.ts
- src/providers/push/fcm/types.ts
- src/providers/push/pubnub/pubnub.provider.ts
- src/providers/push/socketio/types.ts
- src/types.ts
Resolving sonar smells to improve quality gate
GH-111
Fixes #111 
> fix(chore): fix sonar code smells

- package.json
testing the release workflow
GH-00
Testing the release workflow action
Fixes # (issue)
> fix(chore): dummy commit

- catalog-info.yaml
- docs/index.md
- mkdocs.yml
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue)
> techdocs-added

- package-lock.json
- package.json
- src/__tests__/mock-sdk.ts
- src/providers/email/ses/ses.provider.ts
- src/providers/push/pubnub/pubnub.provider.ts
- src/providers/push/pubnub/types.ts
- src/providers/push/socketio/socketio.provider.ts
loopback version updates
GH-171
loopback version updates
Fixes #171 
> chore(deps): loopback version updates

- package-lock.json
- package.json
- src/__tests__/mock-sdk.ts
- src/component.ts
- src/providers/push/pubnub/pubnub.provider.ts
- src/providers/push/pubnub/types.ts
BREAKING CHANGE:
Loopback package version update
Update the lb4 dependencies as lb4 dropped support for node 16 or lower
Fixes #176 
> feat(deps): update lb4 dependencies

- .github/workflows/sync-docs.yaml
since readme moved inside docs folder
GH-00
update the readme path in sync docs action
Fixes # (issue)
> chore(ci-cd): update the readme path in sync docs action

- .github/workflows/main.yaml
- .github/workflows/release.yaml
- package.json
add the missing ci checks for pr
GH-187
add step for changelog generation
add the missing ci checks for pr
Fixes #187 
> fix(ci-cd): add step for changelog generation

- package.json
dummy commit
GH-189
dummy commmit
Fixes #189
> fix(ci-cd): version bump for release

- package.json
commit for major version bump
BREAKING CHANGE:
yes
GH-211
commit for major version bump
Fixes #211 
> feat(provider): previous change was breaking
